name: appium-chromedriver Functional Tests

on:
  pull_request:
    branches: [main]
    paths: ['packages/chromedriver/**', '.github/workflows/chromedriver-functional-test.yml']

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    env:
      CI: 1
      DISPLAY: :99
      _FORCE_LOGS: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup, install and build
        uses: ./.github/actions/setup-build
        with:
          node-version: lts/*
      - name: Run functional tests
        run: |
          export CHROME_VERSION=$(google-chrome --version | python -c "import sys, re; print(re.search(r'[0-9.]+', sys.stdin.read()).group(0))")
          echo "Version number of the installed Chrome browser: $CHROME_VERSION"
          export MAJOR_CHROME_VERSION=$(python -c "print('.'.join('$CHROME_VERSION'.split('.')[:-1]))")
          echo "Major part of the version number: $MAJOR_CHROME_VERSION"
          MAPPING=packages/chromedriver/config/mapping.json
          if grep -q "$MAJOR_CHROME_VERSION" "$MAPPING"; then
            export CHROMEDRIVER_VERSION=$(grep -m 1 -n "$MAJOR_CHROME_VERSION" "$MAPPING" | cut -d' ' -f4 | tr -d ',"')
            echo "Matching Chromedriver version: $CHROMEDRIVER_VERSION"
          fi
          sudo Xvfb -ac $DISPLAY -screen 0 1280x1024x24 > /dev/null 2>&1 &
          npm run test:e2e --workspace appium-chromedriver
